### ISSUE TITLE
Possible to make redirected links appear available?

### ISSUE THREAD

**Issue by StephenBrown2** [splitbrain/dokuwiki-plugin-redirect#7]
In using the redirect module, I've found that the links being redirected still show up as red, or missing. Would it be possible, or prudent, to change their status to not-missing, so they show up as green links?

**Comment by splitbrain** [comment]
I don't think it's possible currently. One could think about introducing an event in page_exists() but this might have side effects (code might expect that if a page exists, it's raw wiki file does too).

**Comment by nerun** [comment]
I would like such enhancement. I enjoy Redirec plugin, it have advantages over [Page Redirect Plugin](https://www.dokuwiki.org/plugin:pageredirect), the most obvious is the no need to the page really exists and, of course, the fact that all redirects are centralized in the same configuration file that is easy to access from the administrative panel. But for it to be perfect the link on the page would have to appear green. Otherwise it's better to use Page Redirect and create the page just as a redirect.

@splitbrain , where is located `page_exists()`? I want to try to do it myself. Maybe we just need a way to trick page rendering.
